---
- name: Configue webservers with Metricbeat
  hosts: webservers
  become: true
  tasks: 
    # Downloads deb file from ELK stack website
    - name: Metricbeat deb download
      command: curl -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    # Installs deb file using dpkg
    - name: Metricbeat installation
      command: dpkg -i metricbeat-7.4.0-amd64.deb

    # Copies configuration file to webservers
    - name: Copy Metricbeat configuration file
      copy:
        src: /etc/ansible/roles/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    # Enable and Configure Docker Module
    - name: Enable and Configure Docker
      command: sudo metricbeat modules enable docker

    # Metricbeat Setup
    - name: Metricbeat Setup
      command: metricbeat setup

    # Metricbeat Start
    - name: Metricbeat Start
      command: sudo service metricbeat start

    